/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.alfred.desktop.view.corretoras;

import br.com.alfred.desktop.view.interfaces.IDataViewer;
import javax.swing.JDesktopPane;

/**
 *
 * @author thiag
 */
public class CorretorasRegister extends javax.swing.JInternalFrame {

    private IDataViewer refDataViewer;
    private JDesktopPane refMain;
    
    /** Creates new form CorretorasRegister */
    public CorretorasRegister(IDataViewer refDataViewer, JDesktopPane refMain) {
        
        //Inicializando componentes
        initComponents();
        this.refMain = refMain;
        this.refDataViewer = refDataViewer;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descriptonJLabel = new javax.swing.JLabel();
        descriptionJTextField = new javax.swing.JTextField();
        registerCorretoraJButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("Incluir Corretora");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        descriptonJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        descriptonJLabel.setText("Nome da Corretora : ");

        registerCorretoraJButton.setText("Incluir");
        registerCorretoraJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerCorretoraJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptonJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descriptionJTextField)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(registerCorretoraJButton)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptonJLabel)
                    .addComponent(descriptionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerCorretoraJButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerCorretoraJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerCorretoraJButtonActionPerformed
        
        this.refDataViewer.reloadMainTable();
        this.setVisible(false);
        this.refMain.remove(this); //É importante remover para desalocar a memória.
    }//GEN-LAST:event_registerCorretoraJButtonActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        
        //Garantindo que o componente será removido do JDestopPane quando fechado.
        this.setVisible(false);
        this.refMain.remove(this); //É importante remover para desalocar a memória.
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descriptionJTextField;
    private javax.swing.JLabel descriptonJLabel;
    private javax.swing.JButton registerCorretoraJButton;
    // End of variables declaration//GEN-END:variables

}
