/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.alfred.desktop.view.corretoras;

import br.com.alfred.desktop.model.Corretora;
import br.com.alfred.desktop.repository.CorretoraRepository;
import br.com.alfred.desktop.utils.BeanUtil;
import br.com.alfred.desktop.utils.TableUtil;
import br.com.alfred.desktop.view.interfaces.IDataViewer;
import java.util.List;
import java.util.Vector;
import javax.swing.JDesktopPane;

/**
 *
 * @author Thiago Teodoro Rodrigues <thiago.teodoro.rodrigues@gmail.com.br>
 */
public class CorretorasDataViewer extends javax.swing.JInternalFrame implements IDataViewer{
    
    private JDesktopPane refMain;

    /** Creates new form CorretorasDataViewer */
    public CorretorasDataViewer(JDesktopPane refMain) {
        
        //Inicializando componente.
        initComponents();
        this.refMain = refMain;
        
        //Carregando dados da tabela.
        this.reloadMainTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorJPanel = new javax.swing.JPanel();
        addJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        corretorasJTable = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Corretoras");

        colorJPanel.setBackground(new java.awt.Color(255, 255, 255));

        addJButton.setBackground(new java.awt.Color(255, 255, 255));
        addJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        addJButton.setBorder(null);
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout colorJPanelLayout = new javax.swing.GroupLayout(colorJPanel);
        colorJPanel.setLayout(colorJPanelLayout);
        colorJPanelLayout.setHorizontalGroup(
            colorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        colorJPanelLayout.setVerticalGroup(
            colorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        corretorasJTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        corretorasJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        corretorasJTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(corretorasJTable);
        if (corretorasJTable.getColumnModel().getColumnCount() > 0) {
            corretorasJTable.getColumnModel().getColumn(0).setMinWidth(100);
            corretorasJTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            corretorasJTable.getColumnModel().getColumn(0).setMaxWidth(100);
            corretorasJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(colorJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
                
        CorretorasRegister corretorasRegister = new CorretorasRegister(this, this.refMain);
        this.refMain.add(corretorasRegister);
        corretorasRegister.setVisible(true);
    }//GEN-LAST:event_addJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JPanel colorJPanel;
    private javax.swing.JTable corretorasJTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void reloadMainTable() {
        
        //Injeção de dependência
        CorretoraRepository corretoraRepository = BeanUtil.getBean(CorretoraRepository.class);
        List<Corretora> listCorretora = corretoraRepository.findAll();
        
        //Limpados dados da tabela.
        TableUtil.emptyTable(this.corretorasJTable);
        
        //Populando a tabela.
        for(Corretora corretora : listCorretora){
            
            Vector<String> aux = new Vector<>();
            aux.add(String.valueOf(corretora.getId()));
            aux.add((String) corretora.getName());
            
            TableUtil.addLine(this.corretorasJTable, aux);
        }
    }

}
