/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.alfred.desktop.view.fixedIncome;

import br.com.alfred.desktop.utils.ViewUtil;
import br.com.alfred.desktop.view.interfaces.IJInternalFrameMandatoryOperations;
import br.com.alfred.desktop.view.interfaces.IManagerViewer;
import javax.swing.JDesktopPane;

/**
 *
 * @author thiag
 */
public class RegisterFixedIncome extends javax.swing.JInternalFrame implements IManagerViewer{

    private JDesktopPane refMain;
    
    /**
     * Creates new form RegisterFixedIncome
     */
    public RegisterFixedIncome(JDesktopPane refMain) {
        
        //Init
        initComponents();
        
        //refMain
        this.refMain = refMain;
        
        //TODO POPULAR O COMBO BOX
        //TODO POPULAR O COMBO BOX
        //TODO POPULAR O COMBO BOX
        //TODO POPULAR O COMBO BOX
        //TODO POPULAR O COMBO BOX
        //TODO POPULAR O COMBO BOX
        //TODO POPULAR O COMBO BOX
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ttileJLabel = new javax.swing.JLabel();
        codJLabel = new javax.swing.JLabel();
        codJComboBox = new javax.swing.JComboBox<>();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        ttileJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ttileJLabel.setText("Novo Titulo de Renda Fixa");

        codJLabel.setText("Código : ");

        codJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codJComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ttileJLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(codJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(504, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ttileJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codJLabel)
                    .addComponent(codJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        
        this.closeAndDeallocateMemoryFrame();
    }//GEN-LAST:event_formInternalFrameClosed

    private void codJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codJComboBoxActionPerformed

    @Override
    public void setFrameToEditProcess() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void closeAndDeallocateMemoryFrame() {
        
        ViewUtil.closeAndDeallocateMemoryFrame(this, refMain);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> codJComboBox;
    private javax.swing.JLabel codJLabel;
    private javax.swing.JLabel ttileJLabel;
    // End of variables declaration//GEN-END:variables
}
